language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_install:
    - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-cs

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
    - ./tests/run-tests.sh
